public class AuthNetReq_Wrapper {
    public string orderName {get;set;}
    public string ccnum {get;set;}
    public string ccexp {get;set;}
    public string ccsec {get;set;}
    public string amt {get;set;}
    public string firstName {get;set;}
    public string lastName {get;set;}
    public string billStreet {get;set;}
    public string billCity {get;set;}
    public string billState {get;set;}
    public string BillZip {get;set;}
    public string routingNumber {get;set;}
    public string accountNumber {get;set;}
    public string bankAccountType {get;set;}
    public string bankName {get;set;}
    public string bankAccount {get;set;}

    public AuthNetReq_Wrapper() {

    }


}


